name: 'transform'
version: '1.0.0'
config-version: 2

# Configure which "profile" dbt uses for this project
profile: 'transform'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets:        # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_modules"
