config:
  send_anonymous_usage_stats: False

# Define dbt profile
transform:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: warehouse_db
      port: 5432
      user: sho
      pass: password
      dbname: warehouse
      schema: air_quality